-- Cria as tabelas CLIENTE, COMPRA e COMPRA_ITEM (idempotente).
-- Mantem IDs autoincrementais (IDENTITY) e os relacionamentos por chave estrangeira.

IF OBJECT_ID('CLIENTE', 'U') IS NULL
BEGIN
    CREATE TABLE CLIENTE
    (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        CPF NVARCHAR(11) NOT NULL,
        NOME NVARCHAR(100) NOT NULL,

        CONSTRAINT PK_CLIENTE
            PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('COMPRA', 'U') IS NULL
BEGIN
    CREATE TABLE COMPRA
    (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        ID_CLIENTE BIGINT NOT NULL,
        DATA_COMPRA DATETIME NOT NULL,

        CONSTRAINT PK_COMPRA
            PRIMARY KEY (ID),

        CONSTRAINT FK_COMPRA_CLIENTE
            FOREIGN KEY (ID_CLIENTE)
            REFERENCES CLIENTE(ID)
    );
END
GO

IF OBJECT_ID('COMPRA_ITEM', 'U') IS NULL
BEGIN
    CREATE TABLE COMPRA_ITEM
    (
        ID BIGINT IDENTITY(1,1) NOT NULL,
        ID_COMPRA BIGINT NOT NULL,
        ID_PRODUTO BIGINT NOT NULL,
        QUANTIDADE INT NOT NULL,

        CONSTRAINT PK_COMPRA_ITEM
            PRIMARY KEY (ID),

        CONSTRAINT FK_COMPRA_ITEM_COMPRA
            FOREIGN KEY (ID_COMPRA)
            REFERENCES COMPRA(ID),

        CONSTRAINT FK_COMPRA_ITEM_PRODUTO
            FOREIGN KEY (ID_PRODUTO)
            REFERENCES PRODUTOS(ID)
    );
END
GO
