-- Execute no banco CleanArchiteture se as tabelas existirem SEM IDENTITY no campo ID.
-- ATENCAO: apaga todos os dados de PRODUTOS e CATEGORIA.
-- Idempotente: pode ser executado mais de uma vez.

USE CleanArchiteture;
GO

IF OBJECT_ID(N'dbo.PRODUTOS', N'U') IS NOT NULL
    DROP TABLE dbo.PRODUTOS;
GO

IF OBJECT_ID(N'dbo.CATEGORIA', N'U') IS NOT NULL
    DROP TABLE dbo.CATEGORIA;
GO

CREATE TABLE dbo.CATEGORIA
(
    ID             BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    COD_CATEGORIA  NVARCHAR(30) NOT NULL,
    DESC_CATEGORIA NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE dbo.PRODUTOS
(
    ID             BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    COD_PRODUTO    NVARCHAR(30) NOT NULL,
    DESC_PRODUTO   NVARCHAR(100) NOT NULL,
    VLR_PRECO      DECIMAL(18,2) NOT NULL,
    DATA_CADASTRO  DATETIME NOT NULL,
    ID_CATEGORIA   BIGINT NOT NULL,
    CONSTRAINT FK_PRODUTOS_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES dbo.CATEGORIA (ID)
);
GO
